CREATE DATABASE loja_virtual;

USE loja_virtual;

CREATE TABLE PRODUTO (id INT AUTO_INCREMENT, nome 	VARCHAR(50) NOT NULL, descricacao VARCHAR(255), PRIMARY KEY(id)) Engine = InnoDB;

INSERT INTO PRODUTO (nome, descricacao) values ('NOTEBOOK', '')

CREATE TABLE CATEGORIA (ID INT AUTO_INCREMENT, NOME VARCHAR (50) NOT NULL, PRIMARY KEY(ID)) Engine = InnoDB;

INSERT INTO CATEGORIA(NOME) VALUES ('ELETRTRONICOS');

INSERT INTO CATEGORIA(NOME) VALUES ('ELETRODOMESTICOS');

INSERT INTO CATEGORIA(NOME) VALUES ('MOVEIS');

SELECT * FROM CATEGORIA

ALTER TABLE PRODUTO ADD COLUMN CATEGORIA_ID INT;

SELECT * FROM PRODUTO;

ALTER TABLE PRODUTO ADD FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID);

UPDATE PRODUTO SET CATEGORIA_ID = 3 WHERE ID = 17;